# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d27cb7abfc132cf398cc7d58a5807c1fcf249325bc4f70e52ee24ff3a145b9e1e74b40f3579cc25073506a858410458a843a6f12b06b560b1031f77986306f0c

test:
  secret_key_base: 479e4356c77f203053726661328bdb237302fc7b29f47233617bb13b5ba542ed25eac0bfea61000e3c1a46e14e2457b8dfb2f7c222e525bf28523920bece4b58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
